# Generated by Django 4.2.1 on 2023-12-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='numero')),
                ('mensagem', models.TextField(verbose_name='mensagem')),
                ('hr_enviada', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('respondido', models.BooleanField(default=False, verbose_name='respondido')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
                'ordering': ['-hr_enviada'],
            },
        ),
    ]
